language: ruby
rvm:
- 2.3.4
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
deploy:
  provider: s3
  aws_access_key_id: AKIAII2S3GRPXDR4R7NQ
  secret_access_key:
    secure: AcwVOiq885P6XqSBut8pCjmANVL6xk+D3oAPbTH32K1xJShXZtx2h+JOYZU2D19Qp9mAV1sZylR1z45a72ViNGEzzy3zcNQro8XQUZyVxHEF8A66TsbqjluwDUOgkuZnlk9Yq+IWV+uxVags3CNYN+x33xh4IvZlZUgSAL/tn2zT8FamxC8THlIJcdy9a7B9HcIYwwSjLhPam+Jw5Q50IPWm/juoWFi3quGNvWBfE9cdj4GJlfdr9dwxwLZuD+NZQx/JIWtEZ8MtxP+NTRvzlPMIGJtK+QjywJ1lvOaLrE1uq77aNHyB9ZBO8e+KNarnK+/1JHo1ZAiQloMUpqkHcGxGsTLYjT3HrKOMBptvaZUuqoPWFmV4qNl2CiQAFpydFTuNqHadwU/gjc1fYig+l5d//Ik1C091zRHTp617BPBZNmX0fc65jYrNcs36x//1h2/+PY+c7n3bauxza2dxCXu1AXwVDfCQ5jP1F3P/LpQSQUDRxXjjG/6JcYdS5C/qzvFWTgV/1leiuBCxfTrNAeuyhVt0o5v+4HbxtJ5Q5XICpILqu3Zbd5ZSQr4qwomHflSwJFUbGdCBqKPmk0JKdqDS5L+Ir7ayI3cw1zTnPKXcZZDeaxtTA12hSkeagc5rs7hxrr3TJ8r8oNPC8jF5EuSTItuC9AFGY1cf8ILoVQg=
  bucket: michael.johnsey.me
