language: ruby
rvm:
- 2.3.4
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
deploy:
  provider: s3
  aws_access_key_id: AKIAII2S3GRPXDR4R7NQ
  secret_access_key:
    secure: HzpM8l1h/uJYPYIHW8qYSAMJSY5m2c7sQV1bSJ+Qu2F4Bc3H3q5g+qxH6v32YVN33N60cf5iiPap5b7HCtsDL3rVTf2cNYgSYT4xBLIoeFd0p+rS/N25Qlaufy3YlUpsB6cGd3Vf1Xf2ZtmlxnCYy7ZpowEt3JST4el+PDh7GCCdn7oWz3r0/HPF5ZCrKH4dV0nKkBOp8qwcFG1M58LPgIn3Vl9S3NCnaJGqxHHWG45a57DzhVRXyHOOWBXDEqKRFkFz2Wk6Rwu3U+sTupxus8LQCcCG5yR2qyMck2fwla1QmjPToeccEsdk28/Styju9L7tQoODAXt5o9EutL2qRZMZgfIMb9IUbulRlV31jUKD2nnUrxZKCGoe88h6IJjd+m95yzDL7FLtmWrTSPMrOCT+0RTxXYpjXTKRmO8jiOTIVIjrT6IFUxaYJvhA66RnjklgDO5U5YWVoCW0Rgp9s1u65xa+oyoFPAqVlpo2MhGiQXROPTTZSi8SOgRQcX8rI5t8893dOM15v6BSV4hpJVq28/JSzGixCDy2K397ZX1Gi0OwWv8irxuxe7ZjQCPB7hfVRbQPzV+pcWo1nmAzQgYLvclUeBNAu/5uqPFtvJ0dF+NIK5hx8TyvHONbr3yoWoajfXXXDECvwkWcMxam6bgk8b5uQZF00CQVo5xpVkE=
  bucket: michael.johnsey.me
