language: ruby
rvm:
- 2.3.4
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAII2S3GRPXDR4R7NQ
  secret_access_key:
    secure: YtODIzpufOI7w7e4mEsvpE9AtDMvkw6R69dlKMa7+s90ASkWduDlUpKketPRYVmF5VJG0xyYE9iTNK8Vw9LiS/Ad0wY3U/tSAYho1vUcbsg8wZh04BuhHCoxQo+Sq2Z2myMqHh+98I/vvvqyiee5fcWMuhDYS68zz301T8YjtvPRJ29DI1+suA2NaAZKt158BPi0mwafmBNqQcMoFFtPy78RTOtdIO9W7CDTu53Trn6SK/UGAdRVTytZU5kF/FdopLeAWoD/fQlAEiV/rc6IAhEY45cVpYsbWAZXZ1QdHr1dmEB46H/oqx80yL+4T1yb19lo80Trvb/HhSUVYfdil4ld3/taLXYFXPs+H9w30VxATGHdUxrKt49z1eMxrefmQxTZ0kAW1nLmqfidTl0AlN8zLi65QlQi1kIH2Jt7p8b5XIHN2UWM3/W0tNOChNj/qCLl2n8BqMr0NhNdtZalI5avFp3Cs7lKo5qLKC9IQg3xZYIJ+WP7SbsCLJSrDIje66RrP3shtDM4+UCzoxYIX6G1mm1gYODcQ+E/vHUDTqmG8oaCZ/FPpbppJb6WL39rvEGPZtb6YUFjwdZGznhygfnFwEcRnP/fxmMqAeZO6ck2N7yyIED8EH/zcTEREoyzRonK4K+EulilgvNE0WESE+3lRRZTEW9ujUXYjfD9p1Y=
  bucket: michael.johnsey.me
  local-dir: _site
  acl: public_read
  on:
    repo: mjohnsey/michael.johnsey.me
  skip_cleanup: true
